/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteAaaaArgs } from "./DeleteAaaaArgs";
import { AaaaCountArgs } from "./AaaaCountArgs";
import { AaaaFindManyArgs } from "./AaaaFindManyArgs";
import { AaaaFindUniqueArgs } from "./AaaaFindUniqueArgs";
import { Aaaa } from "./Aaaa";
import { AaaaService } from "../aaaa.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Aaaa)
export class AaaaResolverBase {
  constructor(
    protected readonly service: AaaaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Aaaa",
    action: "read",
    possession: "any",
  })
  async _aaaasMeta(
    @graphql.Args() args: AaaaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Aaaa])
  @nestAccessControl.UseRoles({
    resource: "Aaaa",
    action: "read",
    possession: "any",
  })
  async aaaas(@graphql.Args() args: AaaaFindManyArgs): Promise<Aaaa[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Aaaa, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Aaaa",
    action: "read",
    possession: "own",
  })
  async aaaa(@graphql.Args() args: AaaaFindUniqueArgs): Promise<Aaaa | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Aaaa)
  @nestAccessControl.UseRoles({
    resource: "Aaaa",
    action: "delete",
    possession: "any",
  })
  async deleteAaaa(@graphql.Args() args: DeleteAaaaArgs): Promise<Aaaa | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
